name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'



jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"
      
      - name: Run unit tests
        run: echo "Running unit tests"




  build-and-push-dockerhub:
    name: Continuous Delivery to Docker Hub
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME